ALTER TABLE servers
    ADD COLUMN cpu_model TEXT,
    ADD COLUMN socket_count INTEGER,
    ADD COLUMN cpu_clock_mhz DOUBLE PRECISION;

ALTER TABLE server_metrics
    ADD COLUMN load_1 DOUBLE PRECISION,
    ADD COLUMN load_5 DOUBLE PRECISION,
    ADD COLUMN load_15 DOUBLE PRECISION,
    ADD COLUMN cpu_user_pct DOUBLE PRECISION,
    ADD COLUMN cpu_system_pct DOUBLE PRECISION,
    ADD COLUMN cpu_iowait_pct DOUBLE PRECISION,
    ADD COLUMN cpu_steal_pct DOUBLE PRECISION,
    ADD COLUMN mem_buffers BIGINT,
    ADD COLUMN mem_cached BIGINT,
    ADD COLUMN swap_used BIGINT,
    ADD COLUMN swap_total BIGINT;
